notifications:
  email: false
language: csharp
solution: Trilogy.sln
install:
  - nuget restore Trilogy.sln
  - nuget install NUnit.ConsoleRunner -Version 3.6.0 -OutputDirectory packages
script:
  - xbuild /p:Configuration=Release ./Trilogy.Tests/Trilogy.Tests.sln
  - mono ./packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./Trilogy.Tests/bin/Release/Trilogy.Tests.dll
